<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'repositories.ticket.in_memory' shared service.

include_once $this->targetDirs[3].'/src/Tiquette/Domain/TicketRepository.php';
include_once $this->targetDirs[3].'/src/Tiquette/Infrastructure/Repositories/InMemoryTicketRepository.php';

return $this->services['repositories.ticket.in_memory'] = new \Tiquette\Infrastructure\Repositories\InMemoryTicketRepository();
