<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'repositories.ticket.dbal' shared service.

include_once $this->targetDirs[3].'/src/Tiquette/Domain/TicketRepository.php';
include_once $this->targetDirs[3].'/src/Tiquette/Infrastructure/Repositories/DbalTicketRepository.php';

return $this->services['repositories.ticket.dbal'] = new \Tiquette\Infrastructure\Repositories\DbalTicketRepository(${($_ = isset($this->services['doctrine.dbal.default_connection']) ? $this->services['doctrine.dbal.default_connection'] : $this->load(__DIR__.'/getDoctrine_Dbal_DefaultConnectionService.php')) && false ?: '_'});
