<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxgwbhc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxgwbhc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVxgwbhc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVxgwbhc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVxgwbhc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vxgwbhc',
    'container.build_id' => '1dd372d5',
    'container.build_time' => 1517302888,
));
